name: med_lot_manager
description: Medication lot management frontend with Dio, secure auth, and repository layer.
publish_to: "none"
version: 0.2.0

environment:
  sdk: ">=2.18.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  dio: ^5.1.2
  flutter_secure_storage: ^8.0.0
  uuid: ^3.0.7
  intl: ^0.18.0
  fl_chart: ^0.68.0
  qr_flutter: ^4.1.0
  mobile_scanner: ^5.2.3
  flutter_local_notifications: ^17.2.3
  permission_handler: ^11.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
